import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <a href="/api/1s">/1s</a>
        <a href="/api/5s">/5s</a>
        <a href="/api/10s">/10s</a>
      </main> 
    </div>
  )
}
