import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href="/api/1s">/1s</Link>
        <Link href="/api/5s">/5s</Link>
        <Link href="/api/10s">/10s</Link>
      </main> 
    </div>
  )
}
